Continuing.
Program received signal SIGSEGV, Segmentation fault.
test1 () at faultstatus.c:125
125		*BADADDR = 'x';
Continuing.
Program received signal SIGSEGV, Segmentation fault.
test2 () at faultstatus.c:130
130		mapping[0] = 'x';
Continuing.
Program received signal SIGBUS, Bus error.
test3 () at faultstatus.c:135
135		mapping[FILESIZE+10];
Continuing.
Program received signal SIGFPE, Arithmetic exception.
